---
driver:
  name: vagrant

provisioner:
  name: chef_zero

client_rb:
  treat_deprecation_warnings_as_errors: true
  resource_cloning: false

verifier: inspec

platforms:
- name: ubuntu-15.04

suites:
# - name: delete_from_list
#   run_list:
#     - recipe[test::delete_from_list]
- name: add_to_list
  run_list:
    - recipe[test::add_to_list]
